jump_to_django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

jump_to_django/pybo/urls.py
from django.urls import path

from pybo.views import base_views, question_views, answer_views, comment_views, vote_views

# URL 별칭 사용 시 중복을 피하기 위해 URL namespace를 설정
app_name = 'pybo'

urlpatterns = [
     # base_views.py
     path('',
          base_views.index, name='index'),
     path('<int:question_id>/',
          base_views.detail, name='detail'),

     # question_views.py
     path('question/create/',
          question_views.question_create, name='question_create'),
     path('question/modify/<int:question_id>/',
          question_views.question_modify, name='question_modify'),
     path('question/delete/<int:question_id>/',
          question_views.question_delete, name='question_delete'),

     # answer_views.py
     path('answer/create/<int:question_id>/',
          answer_views.answer_create, name='answer_create'),
     path('answer/modify/<int:answer_id>/',
          answer_views.answer_modify, name='answer_modify'),
     path('answer/delete/<int:answer_id>/',
          answer_views.answer_delete, name='answer_delete'),

     # comment_views.py
     path('comment/create/question/<int:question_id>/',
          comment_views.comment_create_question, name='comment_create_question'),
     path('comment/modify/question/<int:comment_id>/',
          comment_views.comment_modify_question, name='comment_modify_question'),
     path('comment/delete/question/<int:comment_id>/',
          comment_views.comment_delete_question, name='comment_delete_question'),
     path('comment/create/answer/<int:answer_id>/',
          comment_views.comment_create_answer, name='comment_create_answer'),
     path('comment/modify/answer/<int:comment_id>/',
          comment_views.comment_modify_answer, name='comment_modify_answer'),
     path('comment/delete/answer/<int:comment_id>/',
          comment_views.comment_delete_answer, name='comment_delete_answer'),

     # vote_views.py
     path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
     path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

jump_to_django/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    # User모델은 django.contrib.auth앱이 제공하는 사용자 모델이다. cf) author 속성 추가 후 makemigrations를 하면 오류 - 해결방법: https://wikidocs.net/71306
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')  # author 속성에 저장해야 하는 사용자 객체는 로그인 후 request 객체를 통해 얻을 수 있다.
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)  # blank=True는 form.is_valid()를 통한 입력 데이터 검사 시 값이 없어도 된다는 의미
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가
    #  related_name속성을 안 쓰면 Question 모델에서 사용한 author와 voter가 모두 User 모델과 연결되어 있기 때문에 User.question_set를 쓸 때 기준을 뭘로 할 지 명확하지 않아서 에러
    #  특정 사용자가 작성한 질문을 얻기 위해서는 some_user.author_question.all() 처럼 사용
    #  마찬가지로 특정 사용자가 투표한 질문을 얻기 위해서는 some_user.voter_question.all() 처럼 사용(some_user는 특정 사용자를 의미)

    def __str__(self):
        return self.subject
        # <Question: Question object (1)>를 <Question: pybo가 무엇인가요?>로 출력되게 해줌

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')  # Question의 author 설명과 동일
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)  # blank=True는 form.is_valid()를 통한 입력 데이터 검사 시 값이 없어도 된다는 의미
    voter = models.ManyToManyField(User, related_name='voter_answer')
    
    # 장고에서 사용하는 속성(Field) 타입: https://docs.djangoproject.com/en/3.0/ref/models/fields/#field-types

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    # 만약 질문에 댓글이 작성될 경우에는 question에 값이 저장되고 답변에 댓글이 작성될 경우에는 answer에 값이 저장될 것이다.
    # 따라서 댓글 모델의 question 또는 answer 둘 중에 하나에만 값이 저장되므로 두 개의 속성은 모두 null=True, blank=True 를 설정해야 한다.

'''
# 장고 셸 실행
(mysite) c:\projects\mysite>python manage.py shell

## Question 생성
>>> from pybo.models import Question, Answer
>>> from django.utils import timezone
>>> q = Question(subject='pybo가 무엇인가요?', content='pybo에 대해서 알고 싶습니다.', create_date=timezone.now())
>>> q.save()
>>> q.id
1


## Question 조회
>>> Question.objects.all()
<QuerySet [<Question: pybo가 무엇인가요?>]>

>>> Question.objects.filter(id=1)
<QuerySet [<Question: pybo가 무엇인가요?>]>

>>> Question.objects.get(id=1)
<Question: pybo가 무엇인가요?>

>>> Question.objects.filter(subject__contains='장고')
<QuerySet [<Question: 장고 모델 질문입니다.>]>
# cf) filter사용법: https://docs.djangoproject.com/en/3.0/topics/db/queries/


## Question 수정
>>> q = Question.objects.get(id=2)
>>> q.subject = 'Django Model Question'
>>> q.save()
>>> q
<Question: Django Model Question>


## Question 삭제
>>> q = Question.objects.get(id=1)
>>> q.delete()
(1, {'pybo.Question': 1})


## Answer 작성
>>> q = Question.objects.get(id=2)
>>> q
<Question: Django Model Question>
>>> from django.utils import timezone
>>> a = Answer(question=q, content='네 자동으로 생성됩니다.', create_date=timezone.now())
>>> a.save()


## Answer로 연결된 Question 조회
>>> a.question
<Question: Django Model Question>


## Qustion으로 Answer 조회
>>> q.answer_set.all()
<QuerySet [<Answer: Answer object (1)>]>

cf)★★
연결모델명_set(예:answer_set)은 상식적으로 생각하면 더 쉽다.
질문 하나에는 여러개의 답변이 가능하므로 q.answer_set이 가능하지만,
답변 하나에는 여러개의 질문이 있을 수 없으므로 a.question_set은 불가능하다.
답변 하나에는 질문 하나만 가능하기 때문에 a.question만 가능하다.
'''

jump_to_django/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

# request.user를 사용하는 함수에 @login_required 데코레이터를 사용해야 한다.
@login_required(login_url='common:login')  # 로그아웃 상태에서 호출되면 자동으로 로그인 화면으로 이동시킨다.
def answer_create(request, question_id):
    '''
    pybo 답변등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    '''
    수정 전 코드
    # Question과 Answer 모델은 서로 ForeignKey 로 연결되어 있기때문에 question.answer_set.create()처럼 사용할 수 있다.
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    # 또는 아래처럼도 가능하다.
    # answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    # answer.save()
    return redirect('pybo:detail', question_id=question.id)
    '''
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장  # request.user는 현재 로그인한 계정의 User 모델 객체
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))  # pybo:detail에 해당하는 HTML 중 answer_answer.id 앵커로 이동한다.
    else:  # 사실 답변 등록은 POST 방식만 사용되기 때문에 if .. else 구문에서 else는 호출되지 않는다. 다만, 여기에서는 패턴의 통일성을 위해 남겨 두었다.
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    '''
    pybo 답변수정
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question_id)
    
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))  # pybo:detail에 해당하는 HTML 중 answer_answer.id 앵커로 이동한다.
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    '''
    pybo 답변삭제
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

jump_to_django/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question
from django.db.models import Q, Count

def index(request):
    '''
    pybo 목록 출력
    '''
    # 입력 파라미터
    # http://localhost:8000/pybo/?page=1 처럼 GET 방식으로 호출된 URL에서 page값을 가져올 때 사용한다. 만약 http://localhost:8000/pybo/ 처럼 page값 없이 호출된 경우에는 디폴트로 1이라는 값을 설정한다.
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    ## 정렬 코드 전 조회
    # question_list = Question.objects.order_by('-create_date')

    # 정렬(조회)
    if so == 'recommend':  # annotate의 Count함수를 사용해서 추천수를 구한다. 이렇게 annotate로 num_voter를 지정하면 filter나 order_by에서 num_voter를 사용할 수 있게 된다.
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')  # 내림차순 정렬
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 검색
    if kw:
        question_list = question_list.filter(  # filter 함수에서 모델 속성에 접근하기 위해서는 이처럼 __ (언더바 두개) 를 이용하여 하위 속성에 접근할 수 있다.
            # cf) subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    # cf) 페이징처리를 위해 장고셸에서 테스트데이터 한 번에 넣기: https://wikidocs.net/71240
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)  # 이렇게 하면 장고 내부적으로는 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하도록 쿼리가 변경된다.
    # cf)page_obj에 있는 속성들 - 템플릿에서 페이징 처리 시 사용: https://wikidocs.net/71240
    
    context = {'question_list': page_obj, 'page': page,  'kw': kw, 'so': so}  ## 'page':page는 안 넘겨줘도 작동 - 점프투장고에서 왜 써놨는지 모르겠음..

    # render 함수는 파이썬 데이터를 템플릿에 적용하여 HTML로 반환하는 함수
    # cf) 템플릿 파일은 HTML 파일과 비슷하지만 장고에서 사용하는 태그를 사용할수 있는 HTML 파일이다.
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    '''
    pybo 내용 출력
    '''
    # question = Question.objects.get(id=question_id) 이 경우, 없는 id로 접속하면 DoesNotExist 에러
    question = get_object_or_404(Question, pk=question_id)  # 에러가 Page not found(404)로 바뀜
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
    
    
# 제네릭 뷰는 추후에

jump_to_django/pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    '''
    pybo 질문댓글등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.question.id), comment.id))  # pybo:detail에 해당하는 HTML 중 comment_comment.id 앵커로 이동한다.
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    '''
    pybo 질문댓글수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.question.id), comment.id))  # pybo:detail에 해당하는 HTML 중 comment_comment.id 앵커로 이동한다.
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    '''
    pybo 질문댓글삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    '''
    pybo 답글댓글등록
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))  # pybo:detail에 해당하는 HTML 중 comment_comment.id 앵커로 이동한다.
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    '''
    pybo 답글댓글수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))  # pybo:detail에 해당하는 HTML 중 comment_comment.id 앵커로 이동한다.
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    '''
    pybo 답글댓글삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

jump_to_django/pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    '''
    pybo 질문추천등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
        '''
        Question 모델의 voter는 여러사람을 추가할 수 있는 ManyToManyField이므로 question.voter.add(request.user) 처럼 add 함수를 사용하여 추천인을 추가해야 한다.
        동일한 사용자가 동일한 질문을 여러번 추천하더라도 추천수가 증가하지는 않는다. ManyToManyField를 사용하더라도 중복은 허용되지 않는다.
        '''
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    '''
    pybo 답글추천등록
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

jump_to_django/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3"> <!-- 현재 페이지의 URL이 디폴트 action으로 설정된다. -->
        <!-- 또는 <form method="post" class="post-form my-3" action="{% url 'pybo:question_create' %}">처럼 action 속성을 명시해줘도 된다.
                하지만 이렇게 하면 question_form.html 템플릿은 "질문 등록" 에서만 사용 가능하다. 이후에 진행할 "질문 수정" 에서는 이 템플릿을 활용할 수가 없다. 왜냐하면 질문 수정일 경우에는 action 값을 달리해야 하기 때문이다.
                동일한 템플릿을 여러 기능에서 함께 사용할 경우에는 이처럼 form의 action 속성을 비워두는 기법을 종종 사용한다.
                우리는 이후에 "질문 수정" 기능을 구현할 때도 question_form.html 템플릿을 사용할 것이므로 action 속성은 비워두도록 하자. -->
        {% csrf_token %}
        <!-- {{ form.as_p }}는 question_create 함수에서 전달한 QuestionForm의 객체로,
                폼에 정의한 subject, content 속성에 해당하는 HTML 코드를 자동으로 생성한다. -->
        <!-- {{ form.as_p }} --> <!-- 부트스트랩을 직접 입힐 수 없기 때문에 forms.py에서 widgets속성을 이용하거나 템플릿에서 해당 코드를 쓰지 않고 아예 직접 폼을 작성한다. -->

        {% if form.errors %}  <!-- form.is_vaild()가 실패할 경우 오류내용 표시 -->
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}"> <!-- {{ form.subject.value|default_if_none:'' }}는 오류가 발생했을 경우 기존에 입력했던 값을 유지하기 위함 -->
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

jump_to_django/templates/pybo/question_list.html
{% extends 'base.html' %}  <!-- base.html 상속 -->
{% load pybo_filter %} <!-- sub필터 사용을 위해 pybo_filter 로드 -->
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center thead-dark">
                <th>번호</th>
                <th>추천</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list %}
            <tr class="text-center">
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                <td>  <!-- page_obj.paginator.count: 전체 개시물 개수, page_obj.start_index: 시작인덱스, forloop.counter0: 현재인덱스 -->
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    {% if question.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                    {% endif %}
                </td>
                <td class="text-left">
                {% comment %} <li><a href="{%/pybo/{{ question.id }}/%}">{{ question.subject }}</a></li> {% endcomment %}
                    <!-- url 별칭 사용 -->
                    <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}  <!-- 답변 개수 표시 -->
                        <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
                <td>{{ question.create_date }}</td>
            <tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <!-- 검색 기능 추가 전 코드
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a> -->
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %} <!-- page_obj.paginator.page_range: 페이지 범위 -->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}  <!-- 현재페이지를 기준으로 페이지 표시 제한 기능(+-5) -->
            {% if page_number == question_list.number %}  <!--  page_obj.number: 현재페이지 번호 -->
            <li class="page-item active" aria-current="page">
                <!-- 검색 기능 추가 전 코드
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <!-- 검색 기능 추가 전 코드
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <!-- 검색 기능 추가 전 코드
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a> -->
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}